server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Mantener solo los contenedores que coinciden con "api"
      - source_labels: [__meta_docker_container_name]
        regex: ".*api.*"
        action: keep

      # Agregar etiquetas basadas en metadatos de Docker
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/?(.*)'
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_image]
        target_label: container_image
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      # Agregar una etiqueta estática "job"
      - target_label: job
        replacement: api_logs

      # Configurar la ruta de los logs
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/${1}/*-json.log